---
- hosts: all
  remote_user: vagrant
  #sudo: yes
  become: yes
  vars:
    old_php_packages:
      - php
      - php-cli
      - php-common
    php_packages:
      - php56w
      - php56w-cli
      - php56w-common
      - php56w-devel
      - php56w-fpm
      - php56w-gd
      - php56w-imap
      - php56w-ldap
      - php56w-mbstring
      - php56w-opcache
      - php56w-pdo
      - php56w-pear
      - php56w-pecl-apcu
      - php56w-xml
      - php56w-xmlrpc
      - php56w-mysql
      - php56w-intl
      - php56w-mcrypt
      #- php56w-mysqlnd
      - php56w-pecl-memcached
      - php56w-pecl-xdebug
    mysql_password: vagrant

  tasks:
    - name: test connection
      ping:
      remote_user: vagrant
    
    - name: install webtatic repo
      yum:
        name: https://mirror.webtatic.com/yum/el6/latest.rpm
        state: present

    - name: Install remi repo
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-6.rpm
        state: present

    - name: ensure apache is at the latest version
      yum:
        name: httpd
        state: installed
    - name: Define php_packages.
      set_fact:
        php_packages: "{{ __php_packages | list }}"
      when: php_packages is not defined
    
  #  - name: Ensure PHP installed packages are removed.
  #    yum:
  #      name: "{{ item }}"
  #      state: removed
  #    with_items: old_php_packages
  #  
    - name: Ensure PHP packages are installed.
      yum:
        name: "{{ item }}"
        state: installed
        enablerepo: webtatic,remi-safe
      with_items:
      - php56w
      - php56w-cli
      - php56w-common
      - php56w-devel
      - php56w-fpm
      - php56w-gd
      - php56w-imap
      - php56w-ldap
      - php56w-mbstring
      - php56w-opcache
      - php56w-pdo
      - php56w-pear
      - php56w-pecl-apcu
      - php56w-xml
      - php56w-xmlrpc
      - php56w-mysql
      - php56w-intl
      - php56w-mcrypt
      #- php56w-mysqlnd
      - php56w-pecl-memcached
      - php56w-pecl-xdebug
      - php70-php
      - php70-php-pdo
      - php70-php-json
      - php70-php-fpm
      - php70-php-common
      - php70-php-mbstring
      - php70-php-xml
      - php70-php-gd
      - php70-php-mysqlnd

    
    - name: Ensure MySQL is stopped
      service:
        name: mysqld
        state: stopped
      ignore_errors: true
    
    - name: Ensure mysql is installed
      yum:
        name: http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
        state: installed
    - name: Install MySQL
      yum: 
        name: mysql-community-server 
        state: installed
        
    - name: Install MySQL-python
      yum: name=MySQL-python state=installed
      tags: mysql
      
    - name: make sure mysql is running
      service: 
        name: mysqld
        state: running
        enabled: yes
    - name: Add database user
      mysql_user: name=vagrant password="{{ mysql_password }}" host=% priv=*.*:ALL
    
    - name: Link Document root
      file: src=/vagrant dest=/var/www/html/www state=link
    
    - name: Add a vhost conf
      copy: src=/vagrant/httpd-vshots.conf dest=/etc/httpd/conf.d/httpd-vshots.conf owner=root group=root mode=644 backup=yes
    
    - name: restart httpd
      service:
        name: httpd
        state: restarted
        enabled: yes
    - name: Make Sure memcache installed
      yum:
        name: memcached
        state: installed
    - name: restart memcache
      service:
        name: memcached
        state: restarted
        enabled: yes

    - name: Make sure redis installed
      yum:
        name: redis
        state: installed

    - name: restart redis server
      service:
        name: redis
        state: restarted
        enabled: yes

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
